import { PDFDocument, PDFPage, PDFFont, rgb, StandardFonts } from 'pdf-lib'
import type { Quotation, QuotationLineItem, QuotationAdjustment, ProductText } from '@/types/database'
import type { PdfSection } from '@/pages/quotations/PdfLayoutDialog'

export interface TenantProfile {
  name:             string
  logo_url?:        string | null
  company_address?: string | null
  company_phone?:   string | null
  company_email?:   string | null
  company_website?: string | null
  contact_person?:  string | null
}

// ── Colors ────────────────────────────────────────────────────────────────────
const C = {
  navy:        rgb(0.086, 0.204, 0.510),
  white:       rgb(1,     1,     1),
  black:       rgb(0.067, 0.067, 0.067),
  muted:       rgb(0.45,  0.45,  0.45),
  faint:       rgb(0.80,  0.80,  0.80),
  tableHeader: rgb(0.945, 0.949, 0.961),
  rowAlt:      rgb(0.975, 0.978, 0.984),
  termsBox:    rgb(0.970, 0.970, 0.970),
  accent:      rgb(0.145, 0.337, 0.922),
  positive:    rgb(0.055, 0.604, 0.408),
  negative:    rgb(0.847, 0.208, 0.208),
  ruleLine:    rgb(0.88,  0.88,  0.88),
  rowRule:     rgb(0.920, 0.920, 0.920),
}

function wrapText(rawText: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const result: string[] = []
  for (const paragraph of rawText.split(/\r?\n/)) {
    const words = paragraph.split(' ')
    let line = ''
    for (const word of words) {
      const test = line ? `${line} ${word}` : word
      if (font.widthOfTextAtSize(test, size) > maxWidth) {
        if (line) result.push(line)
        line = word
      } else {
        line = test
      }
    }
    result.push(line)   // always push, even empty (preserves blank lines between paragraphs)
  }
  return result.length ? result : ['']
}

// ── PDF label translations ────────────────────────────────────────────────────

const PDF_LABELS = {
  en: {
    quotation:        'QUOTATION',
    billTo:           'BILL TO',
    quoteDetails:     'QUOTE DETAILS',
    reference:        'Reference:',
    issued:           'Issued:',
    validUntil:       'Valid until:',
    currency:         'Currency:',
    lineItems:        'LINE ITEMS',
    product:          'Product',
    qty:              'Qty',
    uom:              'UOM',
    unitPrice:        'Unit Price',
    total:            'Total',
    subtotal:         'Subtotal',
    totalLabel:       'TOTAL',
    notes:            'NOTES',
    termsHeader:      'PAYMENT & TERMS',
    termsLines: [
      '• Payment terms: 50% deposit on order confirmation, balance prior to delivery.',
      '• Prices are exclusive of VAT / applicable taxes unless otherwise stated.',
      '• This quotation is valid for 30 days unless a specific validity date is indicated above.',
      '• Delivery timelines will be confirmed upon order placement.',
      '• Thank you for your interest. We look forward to working with you.',
    ],
    validityText: (date: string) => `This quotation is valid until ${date}.`,
    contactText:  'Please contact us to confirm your order.',
    footer:       'Generated by Konfigurator',
    dateLocale:   'en-GB' as const,
  },
  sr: {
    quotation:        'PONUDA',
    billTo:           'NARUČILAC',
    quoteDetails:     'DETALJI PONUDE',
    reference:        'Referenca:',
    issued:           'Datum:',
    validUntil:       'Važi do:',
    currency:         'Valuta:',
    lineItems:        'STAVKE',
    product:          'Proizvod',
    qty:              'Kol.',
    uom:              'JM',
    unitPrice:        'Jed. cena',
    total:            'Ukupno',
    subtotal:         'Međuzbir',
    totalLabel:       'UKUPNO',
    notes:            'NAPOMENE',
    termsHeader:      'PLAĆANJE I USLOVI',
    termsLines: [
      '• Uslovi plaćanja: 50% avans pri potvrdi porudžbine, ostatak pre isporuke.',
      '• Cene ne uključuju PDV / poreze, osim ako nije drugačije naznačeno.',
      '• Ova ponuda važi 30 dana, osim ako je gore naznačen konkretan datum.',
      '• Rokovi isporuke biće potvrđeni pri porudžbini.',
      '• Hvala na interesovanju. Radujemo se saradnji.',
    ],
    validityText: (date: string) => `Ova ponuda važi do ${date}.`,
    contactText:  'Kontaktirajte nas radi potvrde porudžbine.',
    footer:       'Generated by Konfigurator',
    dateLocale:   'sr-Latn-RS' as const,
  },
}

// ── PDF builder ───────────────────────────────────────────────────────────────

export async function buildQuotationPdfBytes(
  tenant: TenantProfile,
  quotation: Quotation,
  productTexts?: Record<string, ProductText[]>,
  globalTexts?: ProductText[],
  layoutSections?: PdfSection[],
  lang: 'en' | 'sr' = 'en',
): Promise<Uint8Array> {
  const L = PDF_LABELS[lang]
  const pdfDoc = await PDFDocument.create()
  const fontR  = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontB  = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const W = 595, H = 842, margin = 48, col = W - margin * 2

  // ── Page management ────────────────────────────────────────────────────────
  let page: PDFPage = pdfDoc.addPage([W, H])
  let y = H - margin

  function newPage() {
    drawFooter()
    page = pdfDoc.addPage([W, H])
    y = H - margin
  }

  function ensureSpace(needed: number) {
    if (y - needed < margin + 56) newPage()
  }

  // ── Drawing helpers ────────────────────────────────────────────────────────
  function text(str: string, x: number, yPos: number, size: number, font: PDFFont, color = C.black) {
    str = str.replace(/[\x00-\x09\x0b-\x1f\x7f]/g, ' ')  // strip control chars WinAnsi can't encode
    if (!str) return
    page.drawText(str, { x, y: yPos, size, font, color })
  }

  function rText(str: string, rightX: number, yPos: number, size: number, font: PDFFont, color = C.black) {
    const w = font.widthOfTextAtSize(str, size)
    text(str, rightX - w, yPos, size, font, color)
  }

  function rule(yPos: number, color = C.ruleLine, x1 = margin, x2 = W - margin) {
    page.drawLine({ start: { x: x1, y: yPos }, end: { x: x2, y: yPos }, thickness: 0.5, color })
  }

  function drawFooter() {
    const fy = margin + 16
    rule(fy + 12, C.ruleLine)
    const validityText = quotation.valid_until
      ? L.validityText(new Date(quotation.valid_until).toLocaleDateString(L.dateLocale, { dateStyle: 'long' }))
      : L.contactText
    text(validityText, margin, fy, 8, fontR, C.muted)
    rText(L.footer, W - margin, fy, 8, fontR, C.faint)
  }

  // ── Section 1: Header — logo left, quotation title right ──────────────────
  const logoBoxW = 140, logoBoxH = 76
  const logoBoxX = margin, logoBoxY = H - margin - logoBoxH

  // Try to embed logo image; fall back to gray placeholder
  let logoEmbedded = false
  if (tenant.logo_url) {
    try {
      const buf = await fetch(tenant.logo_url).then(r => r.arrayBuffer())
      const isPNG = tenant.logo_url.toLowerCase().includes('.png')
      const img   = isPNG ? await pdfDoc.embedPng(buf) : await pdfDoc.embedJpg(buf)
      const dims  = img.scaleToFit(logoBoxW, logoBoxH)
      const imgX  = logoBoxX + (logoBoxW - dims.width) / 2
      const imgY  = logoBoxY + (logoBoxH - dims.height) / 2
      page.drawImage(img, { x: imgX, y: imgY, width: dims.width, height: dims.height })
      logoEmbedded = true
    } catch {
      // fall through to placeholder
    }
  }

  if (!logoEmbedded) {
    page.drawRectangle({ x: logoBoxX, y: logoBoxY, width: logoBoxW, height: logoBoxH, color: rgb(0.93, 0.93, 0.93), borderColor: rgb(0.80, 0.80, 0.80), borderWidth: 0.5 })
    const placeholderLabel = tenant.name.toUpperCase()
    const placeholderW = fontB.widthOfTextAtSize(placeholderLabel, 9)
    text(placeholderLabel, logoBoxX + (logoBoxW - placeholderW) / 2, logoBoxY + logoBoxH / 2 - 4, 9, fontB, C.muted)
  }

  // Right: QUOTATION title + ref/dates
  const issueDate = new Date(quotation.created_at).toLocaleDateString(L.dateLocale, { dateStyle: 'long' })
  const qLabel = L.quotation
  text(qLabel, W - margin - fontB.widthOfTextAtSize(qLabel, 22), H - margin - 28, 22, fontB, C.navy)
  rText(`Ref: ${quotation.reference_number}`, W - margin, H - margin - 40, 9, fontR, C.muted)
  rText(`${L.issued} ${issueDate}`, W - margin, H - margin - 52, 9, fontR, C.muted)
  if (quotation.valid_until) {
    const expDate = new Date(quotation.valid_until).toLocaleDateString(L.dateLocale, { dateStyle: 'long' })
    rText(`${L.validUntil} ${expDate}`, W - margin, H - margin - 64, 9, fontR, C.muted)
  }

  // Navy accent stripe
  const stripeY = H - margin - logoBoxH - 10
  page.drawRectangle({ x: 0, y: stripeY, width: W, height: 6, color: C.navy })

  // Sender info row below accent stripe
  y = stripeY - 16
  text(tenant.name.toUpperCase(), margin, y, 8.5, fontB, C.black)
  y -= 13
  const senderParts = [
    tenant.contact_person,
    tenant.company_address,
    tenant.company_phone,
    tenant.company_email,
    tenant.company_website,
  ].filter(Boolean) as string[]
  if (senderParts.length > 0) {
    const senderLine = senderParts.join('  ·  ')
    for (const line of wrapText(senderLine, fontR, 8, col)) {
      text(line, margin, y, 8, fontR, C.muted)
      y -= 12
    }
  }

  y -= 10
  rule(y)
  y -= 22

  // ── Section 3: Two-column customer / quote-meta block ─────────────────────
  const halfCol   = (col - 20) / 2
  const leftX     = margin
  const rightX    = margin + halfCol + 20
  const sectionTopY = y

  // Left: BILL TO
  text(L.billTo, leftX, y, 7.5, fontB, C.muted)
  y -= 16

  text(quotation.customer_name, leftX, y, 13, fontB, C.black)
  y -= 15
  text(quotation.customer_email, leftX, y, 10, fontR, C.accent)
  y -= 13

  if (quotation.customer_company) { text(quotation.customer_company, leftX, y, 9, fontR, C.muted); y -= 12 }
  if (quotation.customer_phone)   { text(quotation.customer_phone,   leftX, y, 9, fontR, C.muted); y -= 12 }
  if (quotation.customer_address) {
    for (const line of wrapText(quotation.customer_address, fontR, 9, halfCol)) {
      text(line, leftX, y, 9, fontR, C.muted); y -= 12
    }
  }

  // Right: QUOTE DETAILS (rendered alongside the left column)
  let ry = sectionTopY
  text(L.quoteDetails, rightX, ry, 7.5, fontB, C.muted)
  ry -= 16

  function detailRow(label: string, value: string) {
    text(label, rightX, ry, 9, fontR, C.muted)
    rText(value, W - margin, ry, 9, fontB, C.black)
    ry -= 13
  }

  detailRow(L.reference, quotation.reference_number)
  detailRow(L.issued, issueDate)
  if (quotation.valid_until) {
    detailRow(L.validUntil, new Date(quotation.valid_until).toLocaleDateString(L.dateLocale, { dateStyle: 'long' }))
  }
  detailRow(L.currency, quotation.currency)

  // Vertical separator between columns
  const sectionBottomY = Math.min(y, ry)
  page.drawLine({
    start: { x: margin + halfCol + 10, y: sectionTopY + 4 },
    end:   { x: margin + halfCol + 10, y: sectionBottomY - 4 },
    thickness: 0.5, color: C.ruleLine,
  })

  y = sectionBottomY - 16
  rule(y)
  y -= 20

  // ── Section 4: Line items table ────────────────────────────────────────────
  const items = (Array.isArray(quotation.line_items) ? quotation.line_items : []) as unknown as QuotationLineItem[]

  if (items.length > 0) {
    ensureSpace(40)
    text(L.lineItems, margin, y, 7.5, fontB, C.muted)
    y -= 22

    // Table header
    ensureSpace(26)
    page.drawRectangle({ x: margin, y: y - 6, width: col, height: 24, color: C.tableHeader })

    const colQty   = col * 0.56
    const colUOM   = col * 0.66
    const colUnit  = col * 0.76
    const colTotal = col

    text('#',          margin + 6,            y, 8.5, fontB, C.muted)
    text(L.product,    margin + 24,           y, 8.5, fontB, C.muted)
    text(L.qty,        margin + colQty,       y, 8.5, fontB, C.muted)
    text(L.uom,        margin + colUOM,       y, 8.5, fontB, C.muted)
    text(L.unitPrice,  margin + colUnit,      y, 8.5, fontB, C.muted)
    rText(L.total,     margin + colTotal - 6, y, 8.5, fontB, C.muted)
    y -= 22

    for (let i = 0; i < items.length; i++) {
      const item      = items[i]
      const lineTotal = item.unit_price * item.quantity
      const cfg       = Array.isArray(item.configuration) ? item.configuration : []
      const allTexts_ = productTexts?.[item.product_id] ?? []
      const texts_    = allTexts_.filter(pt => pt.language === lang)

      // Compute exact row height
      const wrapW = col - 28 - colUnit
      let rowHeight = 12  // product name line
      if (item.product_sku) rowHeight += 11
      rowHeight += cfg.length * 11
      for (const pt of texts_) {
        rowHeight += 11  // label
        rowHeight += wrapText(pt.content, fontR, 8, wrapW).length * 11
      }
      rowHeight += 10  // bottom padding
      ensureSpace(rowHeight)

      // Alternating row bg (covers full row plus 4pt top padding)
      const bgColor = i % 2 === 1 ? C.rowAlt : undefined
      if (bgColor) page.drawRectangle({ x: margin, y: y - rowHeight + 4, width: col, height: rowHeight + 4, color: bgColor })

      const rowStartY = y

      // Row number
      text(`${i + 1}`, margin + 6, y, 9, fontR, C.muted)

      // Product name
      text(item.product_name, margin + 24, y, 10, fontB, C.black)
      y -= 12

      // SKU
      if (item.product_sku) {
        text(`SKU: ${item.product_sku}`, margin + 24, y, 8, fontR, C.muted)
        y -= 11
      }

      // Configuration rows
      for (const c of cfg) {
        text(`${c.characteristic_name}: ${c.value_label}`, margin + 24, y, 8, fontR, C.muted)
        y -= 11
      }

      // Product texts
      if (texts_.length > 0) {
        for (const pt of texts_) {
          text(pt.label + ':', margin + 24, y, 7.5, fontB, C.muted)
          y -= 11
          for (const line of wrapText(pt.content, fontR, 8, col - 28 - colUnit)) {
            text(line, margin + 28, y, 8, fontR, C.muted)
            y -= 11
          }
        }
      }

      // Qty / UOM / Unit price / Total — anchored to product name row
      const numY = rowStartY
      text(String(item.quantity),          margin + colQty,  numY, 9.5, fontR, C.black)
      text(item.unit_of_measure ?? '—',    margin + colUOM,  numY, 9.5, fontR, C.muted)
      text(item.unit_price.toFixed(2),     margin + colUnit, numY, 9.5, fontR, C.black)
      rText(lineTotal.toFixed(2),          margin + colTotal - 6, numY, 9.5, fontB, C.black)

      y -= 8
      rule(y + 2, C.rowRule)
    }
    y -= 10
  }

  // ── Section 5: Financial summary ───────────────────────────────────────────
  rule(y)
  y -= 20

  const adjustments = (Array.isArray(quotation.adjustments) ? quotation.adjustments : []) as unknown as QuotationAdjustment[]
  const summaryLeft = W - margin - 210

  const subtotalStr = `${quotation.subtotal.toFixed(2)} ${quotation.currency}`
  text(L.subtotal, summaryLeft, y, 10, fontR, C.muted)
  rText(subtotalStr, W - margin, y, 10, fontR, C.black)
  y -= 18

  let running = quotation.subtotal
  for (const adj of adjustments) {
    const amount  = adj.mode === 'percent' ? (running * adj.value) / 100 : adj.value
    const sign    = adj.type === 'discount' ? -1 : 1
    const applied = sign * amount
    if (adj.type !== 'discount') running += amount
    else running -= amount

    const label  = `${adj.label} (${adj.type}${adj.mode === 'percent' ? `, ${adj.value}%` : ''})`
    const amtStr = `${applied >= 0 ? '+' : ''}${applied.toFixed(2)} ${quotation.currency}`

    text(label, summaryLeft, y, 9.5, fontR, C.muted)
    rText(amtStr, W - margin, y, 9.5, fontB, applied >= 0 ? C.positive : C.negative)
    y -= 18
  }

  ensureSpace(40)
  rule(y, C.black, summaryLeft)
  y -= 20

  text(L.totalLabel, summaryLeft, y, 10, fontB, C.muted)
  const totalStr = `${quotation.total_price.toFixed(2)} ${quotation.currency}`
  rText(totalStr, W - margin, y - 2, 18, fontB, C.black)
  y -= 38

  // ── Sections 6+: layout-ordered notes, terms, and global text blocks ─────────

  function isSectionVisible(id: string): boolean {
    if (!layoutSections) return true
    const s = layoutSections.find(s => s.id === id)
    return s ? s.visible : true
  }

  function drawNotesSection() {
    if (!quotation.notes) return
    ensureSpace(40)
    rule(y)
    y -= 18
    text(L.notes, margin, y, 7.5, fontB, C.muted)
    y -= 14
    for (const line of wrapText(quotation.notes, fontR, 10, col - 16)) {
      ensureSpace(14)
      text(line, margin, y, 10, fontR, C.muted)
      y -= 14
    }
    y -= 6
  }

  function drawTermsSection() {
    const termsLines = [L.termsHeader, ...L.termsLines]
    const termsHeight = 12 + termsLines.length * 13
    ensureSpace(termsHeight + 20)
    rule(y)
    y -= 18
    page.drawRectangle({ x: margin, y: y - termsHeight + 14, width: col, height: termsHeight, color: C.termsBox })
    page.drawRectangle({ x: margin, y: y - termsHeight + 14, width: col, height: termsHeight, borderColor: C.ruleLine, borderWidth: 0.5 })
    y -= 4
    for (let i = 0; i < termsLines.length; i++) {
      const isHeader = i === 0
      text(termsLines[i], margin + 10, y, isHeader ? 8 : 8.5, isHeader ? fontB : fontR, isHeader ? C.muted : C.black)
      y -= 13
    }
  }

  function drawGlobalTextSection(txt: ProductText) {
    const contentLines = wrapText(txt.content, fontR, 9.5, col - 16)
    const blockHeight  = 16 + 14 + contentLines.length * 14 + 10
    ensureSpace(blockHeight + 20)
    rule(y)
    y -= 18
    text(txt.label.toUpperCase(), margin, y, 7.5, fontB, C.muted)
    y -= 14
    for (const line of contentLines) {
      ensureSpace(14)
      text(line, margin, y, 9.5, fontR, C.black)
      y -= 14
    }
    y -= 6
  }

  // Determine rendering order: either from layoutSections (user-configured) or default
  const defaultOrder: PdfSection[] = [
    { id: 'notes', label: 'Notes', visible: true },
    { id: 'terms', label: 'Terms & Conditions', visible: true },
    ...(globalTexts ?? []).filter(gt => gt.language === lang).map(gt => ({ id: `text-${gt.id}`, label: gt.label, visible: true, textId: gt.id })),
  ]
  const orderedSections = layoutSections
    ? layoutSections.filter(s => !s.locked)
    : defaultOrder

  for (const section of orderedSections) {
    if (!section.visible) continue
    if (section.id === 'notes') {
      if (isSectionVisible('notes')) drawNotesSection()
    } else if (section.id === 'terms') {
      if (isSectionVisible('terms')) drawTermsSection()
    } else if (section.textId) {
      const gt = (globalTexts ?? []).find(t => t.id === section.textId && t.language === lang)
      if (gt) drawGlobalTextSection(gt)
    }
  }

  // ── Footer on last page ────────────────────────────────────────────────────
  drawFooter()

  return pdfDoc.save()
}

export function openPdfBlob(bytes: Uint8Array) {
  const blob = new Blob([bytes.buffer as ArrayBuffer], { type: 'application/pdf' })
  const url  = URL.createObjectURL(blob)
  window.open(url, '_blank', 'noopener')
}
