import { PDFDocument, PDFPage, PDFFont, rgb, StandardFonts } from 'pdf-lib'
import type { Quotation, QuotationLineItem, QuotationAdjustment, ProductText } from '@/types/database'

// ── Colors ────────────────────────────────────────────────────────────────────
const C = {
  navy:        rgb(0.086, 0.204, 0.510),
  white:       rgb(1,     1,     1),
  black:       rgb(0.067, 0.067, 0.067),
  muted:       rgb(0.45,  0.45,  0.45),
  faint:       rgb(0.80,  0.80,  0.80),
  tableHeader: rgb(0.945, 0.949, 0.961),
  rowAlt:      rgb(0.975, 0.978, 0.984),
  termsBox:    rgb(0.970, 0.970, 0.970),
  accent:      rgb(0.145, 0.337, 0.922),
  positive:    rgb(0.055, 0.604, 0.408),
  negative:    rgb(0.847, 0.208, 0.208),
  ruleLine:    rgb(0.88,  0.88,  0.88),
  rowRule:     rgb(0.920, 0.920, 0.920),
}

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.split(' ')
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    const test = line ? `${line} ${word}` : word
    if (font.widthOfTextAtSize(test, size) > maxWidth) {
      if (line) lines.push(line)
      line = word
    } else {
      line = test
    }
  }
  if (line) lines.push(line)
  return lines.length ? lines : ['']
}

// ── PDF builder ───────────────────────────────────────────────────────────────

export async function buildQuotationPdfBytes(
  tenantName: string,
  quotation: Quotation,
  productTexts?: Record<string, ProductText[]>
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const fontR  = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontB  = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const W = 595, H = 842, margin = 48, col = W - margin * 2

  // ── Page management ────────────────────────────────────────────────────────
  let page: PDFPage = pdfDoc.addPage([W, H])
  let y = H - margin

  function newPage() {
    drawFooter()
    page = pdfDoc.addPage([W, H])
    y = H - margin
  }

  function ensureSpace(needed: number) {
    if (y - needed < margin + 56) newPage()
  }

  // ── Drawing helpers ────────────────────────────────────────────────────────
  function text(str: string, x: number, yPos: number, size: number, font: PDFFont, color = C.black) {
    if (!str) return
    page.drawText(str, { x, y: yPos, size, font, color })
  }

  function rText(str: string, rightX: number, yPos: number, size: number, font: PDFFont, color = C.black) {
    const w = font.widthOfTextAtSize(str, size)
    text(str, rightX - w, yPos, size, font, color)
  }

  function rule(yPos: number, color = C.ruleLine, x1 = margin, x2 = W - margin) {
    page.drawLine({ start: { x: x1, y: yPos }, end: { x: x2, y: yPos }, thickness: 0.5, color })
  }

  function drawFooter() {
    const fy = margin + 16
    rule(fy + 12, C.ruleLine)
    const validityText = quotation.valid_until
      ? `This quotation is valid until ${new Date(quotation.valid_until).toLocaleDateString('en-GB', { dateStyle: 'long' })}.`
      : 'Please contact us to confirm your order.'
    text(validityText, margin, fy, 8, fontR, C.muted)
    rText('Generated by Konfigurator', W - margin, fy, 8, fontR, C.faint)
  }

  // ── Section 1: Navy header bar ─────────────────────────────────────────────
  const barH = 64
  page.drawRectangle({ x: 0, y: H - barH, width: W, height: barH, color: C.navy })

  const tenantStr = tenantName.toUpperCase()
  text(tenantStr, margin, H - barH + 22, 10, fontB, C.white)

  const qLabel = 'QUOTATION'
  const qLabelW = fontB.widthOfTextAtSize(qLabel, 20)
  text(qLabel, W - margin - qLabelW, H - barH + 20, 20, fontB, C.white)

  y = H - barH - 14

  // ── Section 2: Ref + dates row ─────────────────────────────────────────────
  const issueDate = new Date(quotation.created_at).toLocaleDateString('en-GB', { dateStyle: 'long' })
  text(`Issued: ${issueDate}`, margin, y, 9, fontR, C.muted)
  rText(`Ref: ${quotation.reference_number}`, W - margin, y, 9, fontR, C.muted)
  y -= 13

  if (quotation.valid_until) {
    const expDate = new Date(quotation.valid_until).toLocaleDateString('en-GB', { dateStyle: 'long' })
    rText(`Valid until: ${expDate}`, W - margin, y, 9, fontR, C.muted)
  }
  y -= 18

  rule(y)
  y -= 22

  // ── Section 3: Two-column customer / quote-meta block ─────────────────────
  const halfCol   = (col - 20) / 2
  const leftX     = margin
  const rightX    = margin + halfCol + 20
  const sectionTopY = y

  // Left: BILL TO
  text('BILL TO', leftX, y, 7.5, fontB, C.muted)
  y -= 16

  text(quotation.customer_name, leftX, y, 13, fontB, C.black)
  y -= 15
  text(quotation.customer_email, leftX, y, 10, fontR, C.accent)
  y -= 13

  if (quotation.customer_company) { text(quotation.customer_company, leftX, y, 9, fontR, C.muted); y -= 12 }
  if (quotation.customer_phone)   { text(quotation.customer_phone,   leftX, y, 9, fontR, C.muted); y -= 12 }
  if (quotation.customer_address) {
    for (const line of wrapText(quotation.customer_address, fontR, 9, halfCol)) {
      text(line, leftX, y, 9, fontR, C.muted); y -= 12
    }
  }

  // Right: QUOTE DETAILS (rendered alongside the left column)
  let ry = sectionTopY
  text('QUOTE DETAILS', rightX, ry, 7.5, fontB, C.muted)
  ry -= 16

  function detailRow(label: string, value: string) {
    text(label, rightX, ry, 9, fontR, C.muted)
    rText(value, W - margin, ry, 9, fontB, C.black)
    ry -= 13
  }

  detailRow('Reference:', quotation.reference_number)
  detailRow('Issued:', issueDate)
  if (quotation.valid_until) {
    detailRow('Valid until:', new Date(quotation.valid_until).toLocaleDateString('en-GB', { dateStyle: 'long' }))
  }
  detailRow('Currency:', quotation.currency)

  // Vertical separator between columns
  const sectionBottomY = Math.min(y, ry)
  page.drawLine({
    start: { x: margin + halfCol + 10, y: sectionTopY + 4 },
    end:   { x: margin + halfCol + 10, y: sectionBottomY - 4 },
    thickness: 0.5, color: C.ruleLine,
  })

  y = sectionBottomY - 16
  rule(y)
  y -= 20

  // ── Section 4: Line items table ────────────────────────────────────────────
  const items = (Array.isArray(quotation.line_items) ? quotation.line_items : []) as unknown as QuotationLineItem[]

  if (items.length > 0) {
    ensureSpace(40)
    text('LINE ITEMS', margin, y, 7.5, fontB, C.muted)
    y -= 14

    // Table header
    ensureSpace(26)
    page.drawRectangle({ x: margin, y: y - 6, width: col, height: 24, color: C.tableHeader })

    const colQty   = col * 0.56
    const colUOM   = col * 0.66
    const colUnit  = col * 0.76
    const colTotal = col

    text('#',           margin + 6,         y, 8.5, fontB, C.muted)
    text('Product',     margin + 24,        y, 8.5, fontB, C.muted)
    text('Qty',         margin + colQty,    y, 8.5, fontB, C.muted)
    text('UOM',         margin + colUOM,    y, 8.5, fontB, C.muted)
    text('Unit Price',  margin + colUnit,   y, 8.5, fontB, C.muted)
    rText('Total',      margin + colTotal - 6, y, 8.5, fontB, C.muted)
    y -= 22

    for (let i = 0; i < items.length; i++) {
      const item      = items[i]
      const lineTotal = item.unit_price * item.quantity
      const cfg       = Array.isArray(item.configuration) ? item.configuration : []
      const texts_    = productTexts?.[item.product_id] ?? []

      // Estimate row height
      const skuLines  = item.product_sku ? 1 : 0
      const rowHeight = 14 + (skuLines * 11) + cfg.length * 11 + texts_.length * 14 + 10
      ensureSpace(rowHeight)

      // Alternating row bg
      const bgColor = i % 2 === 1 ? C.rowAlt : undefined
      if (bgColor) page.drawRectangle({ x: margin, y: y - rowHeight + 14, width: col, height: rowHeight, color: bgColor })

      const rowStartY = y

      // Row number
      text(`${i + 1}`, margin + 6, y, 9, fontR, C.muted)

      // Product name
      text(item.product_name, margin + 24, y, 10, fontB, C.black)
      y -= 12

      // SKU
      if (item.product_sku) {
        text(`SKU: ${item.product_sku}`, margin + 24, y, 8, fontR, C.muted)
        y -= 11
      }

      // Configuration rows
      for (const c of cfg) {
        text(`${c.characteristic_name}: ${c.value_label}`, margin + 24, y, 8, fontR, C.muted)
        y -= 11
      }

      // Product texts
      if (texts_.length > 0) {
        for (const pt of texts_) {
          text(pt.label + ':', margin + 24, y, 7.5, fontB, C.muted)
          y -= 11
          for (const line of wrapText(pt.content, fontR, 8, col - 28 - colUnit)) {
            text(line, margin + 28, y, 8, fontR, C.muted)
            y -= 11
          }
        }
      }

      // Qty / UOM / Unit price / Total — anchored to product name row
      const numY = rowStartY
      text(String(item.quantity),          margin + colQty,  numY, 9.5, fontR, C.black)
      text(item.unit_of_measure ?? '—',    margin + colUOM,  numY, 9.5, fontR, C.muted)
      text(item.unit_price.toFixed(2),     margin + colUnit, numY, 9.5, fontR, C.black)
      rText(lineTotal.toFixed(2),          margin + colTotal - 6, numY, 9.5, fontB, C.black)

      y -= 8
      rule(y + 2, C.rowRule)
    }
    y -= 10
  }

  // ── Section 5: Financial summary ───────────────────────────────────────────
  rule(y)
  y -= 20

  const adjustments = (Array.isArray(quotation.adjustments) ? quotation.adjustments : []) as unknown as QuotationAdjustment[]
  const summaryLeft = W - margin - 210

  const subtotalStr = `${quotation.subtotal.toFixed(2)} ${quotation.currency}`
  text('Subtotal', summaryLeft, y, 10, fontR, C.muted)
  rText(subtotalStr, W - margin, y, 10, fontR, C.black)
  y -= 18

  let running = quotation.subtotal
  for (const adj of adjustments) {
    const amount  = adj.mode === 'percent' ? (running * adj.value) / 100 : adj.value
    const sign    = adj.type === 'discount' ? -1 : 1
    const applied = sign * amount
    if (adj.type !== 'discount') running += amount
    else running -= amount

    const label  = `${adj.label} (${adj.type}${adj.mode === 'percent' ? `, ${adj.value}%` : ''})`
    const amtStr = `${applied >= 0 ? '+' : ''}${applied.toFixed(2)} ${quotation.currency}`

    text(label, summaryLeft, y, 9.5, fontR, C.muted)
    rText(amtStr, W - margin, y, 9.5, fontB, applied >= 0 ? C.positive : C.negative)
    y -= 18
  }

  ensureSpace(40)
  rule(y, C.black, summaryLeft)
  y -= 20

  text('TOTAL', summaryLeft, y, 10, fontB, C.muted)
  const totalStr = `${quotation.total_price.toFixed(2)} ${quotation.currency}`
  rText(totalStr, W - margin, y - 2, 18, fontB, C.black)
  y -= 38

  // ── Section 6: Notes ───────────────────────────────────────────────────────
  if (quotation.notes) {
    ensureSpace(40)
    rule(y)
    y -= 18
    text('NOTES', margin, y, 7.5, fontB, C.muted)
    y -= 14
    for (const line of wrapText(quotation.notes, fontR, 10, col - 16)) {
      ensureSpace(14)
      text(line, margin, y, 10, fontR, C.muted)
      y -= 14
    }
    y -= 6
  }

  // ── Section 7: Terms & Conditions box ─────────────────────────────────────
  const termsLines = [
    'PAYMENT & TERMS',
    '• Payment terms: 50% deposit on order confirmation, balance prior to delivery.',
    '• Prices are exclusive of VAT / applicable taxes unless otherwise stated.',
    '• This quotation is valid for 30 days unless a specific validity date is indicated above.',
    '• Delivery timelines will be confirmed upon order placement.',
    '• Thank you for your interest. We look forward to working with you.',
  ]

  const termsHeight = 12 + termsLines.length * 13
  ensureSpace(termsHeight + 20)

  rule(y)
  y -= 18

  page.drawRectangle({ x: margin, y: y - termsHeight + 14, width: col, height: termsHeight, color: C.termsBox })
  page.drawRectangle({ x: margin, y: y - termsHeight + 14, width: col, height: termsHeight, borderColor: C.ruleLine, borderWidth: 0.5 })

  y -= 4
  for (let i = 0; i < termsLines.length; i++) {
    const isHeader = i === 0
    text(termsLines[i], margin + 10, y, isHeader ? 8 : 8.5, isHeader ? fontB : fontR, isHeader ? C.muted : C.black)
    y -= 13
  }

  // ── Footer on last page ────────────────────────────────────────────────────
  drawFooter()

  return pdfDoc.save()
}

export function openPdfBlob(bytes: Uint8Array) {
  const blob = new Blob([bytes.buffer as ArrayBuffer], { type: 'application/pdf' })
  const url  = URL.createObjectURL(blob)
  window.open(url, '_blank', 'noopener')
}
