-- Migration 052: Seed "Čelična, djelimično zastakljena vrata" template product
-- Adds a fully configurable steel partially-glazed door with:
--   • Lock type    (radio, 3 options)
--   • Colour       (swatch, 3 options)
--   • Width        (number, mm)
--   • Height       (number, mm)
--   • Hinges       (radio, 3 options)
-- Visualization asset references a GLB with mesh-visibility and dimension rules.
-- The GLB file is generated by scripts/generate_steel_door_model.mjs — upload
-- it to Supabase Storage and update the url below before running this migration.

DO $$
DECLARE
  sys_tid uuid := '00000000-0000-0000-0000-000000000000';

  p_door  uuid;

  c_lock   uuid;
  c_color  uuid;
  c_width  uuid;
  c_height uuid;
  c_hinges uuid;

  v_lock_cyl   uuid;
  v_lock_multi uuid;
  v_lock_smart uuid;

  v_col_black uuid;
  v_col_anthr uuid;
  v_col_white uuid;

  v_hng_std   uuid;
  v_hng_conc  uuid;
  v_hng_heavy uuid;

  cls_door uuid;

BEGIN

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. PRODUCT
-- ═══════════════════════════════════════════════════════════════════════════
  INSERT INTO public.products (
    tenant_id, name, name_i18n,
    description, description_i18n,
    base_price, currency, status,
    is_template, template_category,
    ar_enabled, ar_placement
  ) VALUES (
    sys_tid,
    'Čelična, djelimično zastakljena vrata',
    '{"sr":"Čelična, djelimično zastakljena vrata","en":"Steel Partially Glazed Door","de":"Stahl-Teilverglaste Tür"}',
    'Sigurnosna čelična vrata s djelimičnim zastakljivanjem. Konfigurirajte bravu, boju, dimenzije i šarke prema vašim potrebama.',
    '{"sr":"Sigurnosna čelična vrata s djelimičnim zastakljivanjem. Konfigurirajte bravu, boju, dimenzije i šarke prema vašim potrebama.","en":"Security steel door with partial glazing. Configure lock type, colour, dimensions and hinges to your requirements.","de":"Sicherheits-Stahltür mit Teilverglasung. Konfigurieren Sie Schloss, Farbe, Maße und Scharniere nach Ihren Anforderungen."}',
    850,
    'EUR',
    'published',
    true,
    'Windows & Doors',
    true,
    'wall'
  ) RETURNING id INTO p_door;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. CHARACTERISTICS
-- ═══════════════════════════════════════════════════════════════════════════
  INSERT INTO public.characteristics (tenant_id, name, name_i18n, display_type, sort_order)
    VALUES (sys_tid, 'Brava', '{"sr":"Brava","en":"Lock","de":"Schloss"}', 'radio', 0)
    RETURNING id INTO c_lock;

  INSERT INTO public.characteristics (tenant_id, name, name_i18n, display_type, sort_order)
    VALUES (sys_tid, 'Boja', '{"sr":"Boja","en":"Colour","de":"Farbe"}', 'swatch', 1)
    RETURNING id INTO c_color;

  INSERT INTO public.characteristics (tenant_id, name, name_i18n, display_type, sort_order)
    VALUES (sys_tid, 'Širina (mm)', '{"sr":"Širina (mm)","en":"Width (mm)","de":"Breite (mm)"}', 'number', 2)
    RETURNING id INTO c_width;

  INSERT INTO public.characteristics (tenant_id, name, name_i18n, display_type, sort_order)
    VALUES (sys_tid, 'Visina (mm)', '{"sr":"Visina (mm)","en":"Height (mm)","de":"Höhe (mm)"}', 'number', 3)
    RETURNING id INTO c_height;

  INSERT INTO public.characteristics (tenant_id, name, name_i18n, display_type, sort_order)
    VALUES (sys_tid, 'Šarke', '{"sr":"Šarke","en":"Hinges","de":"Scharniere"}', 'radio', 4)
    RETURNING id INTO c_hinges;

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. CHARACTERISTIC VALUES
-- ═══════════════════════════════════════════════════════════════════════════

  -- Lock values
  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_lock, sys_tid,
      'Standardni cilindar',
      '{"sr":"Standardni cilindar","en":"Standard Cylinder","de":"Standard-Zylinder"}',
      0, 0)
    RETURNING id INTO v_lock_cyl;

  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_lock, sys_tid,
      'Višetačkasto zaključavanje',
      '{"sr":"Višetačkasto zaključavanje","en":"Multi-Point Lock","de":"Mehrpunktverriegelung"}',
      120, 1)
    RETURNING id INTO v_lock_multi;

  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_lock, sys_tid,
      'Smart brava',
      '{"sr":"Smart brava","en":"Smart Lock","de":"Smart-Schloss"}',
      280, 2)
    RETURNING id INTO v_lock_smart;

  -- Colour values
  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_color, sys_tid,
      'RAL 9005 Crna',
      '{"sr":"RAL 9005 Crna","en":"RAL 9005 Black","de":"RAL 9005 Schwarz"}',
      0, 0)
    RETURNING id INTO v_col_black;

  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_color, sys_tid,
      'RAL 7016 Antracit',
      '{"sr":"RAL 7016 Antracit","en":"RAL 7016 Anthracite","de":"RAL 7016 Anthrazit"}',
      30, 1)
    RETURNING id INTO v_col_anthr;

  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_color, sys_tid,
      'RAL 9010 Bijela',
      '{"sr":"RAL 9010 Bijela","en":"RAL 9010 White","de":"RAL 9010 Weiß"}',
      30, 2)
    RETURNING id INTO v_col_white;

  -- Hinge values
  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_hinges, sys_tid,
      'Standardne šarke',
      '{"sr":"Standardne šarke","en":"Standard Hinges","de":"Standard-Scharniere"}',
      0, 0)
    RETURNING id INTO v_hng_std;

  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_hinges, sys_tid,
      'Skrivene šarke',
      '{"sr":"Skrivene šarke","en":"Concealed Hinges","de":"Verdeckte Scharniere"}',
      80, 1)
    RETURNING id INTO v_hng_conc;

  INSERT INTO public.characteristic_values
    (characteristic_id, tenant_id, label, label_i18n, price_modifier, sort_order)
    VALUES (c_hinges, sys_tid,
      'Teške industrijske šarke',
      '{"sr":"Teške industrijske šarke","en":"Heavy-Duty Hinges","de":"Schwerlastscharniere"}',
      150, 2)
    RETURNING id INTO v_hng_heavy;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. LEGACY product_characteristics (for admin panel compatibility)
-- ═══════════════════════════════════════════════════════════════════════════
  INSERT INTO public.product_characteristics
    (product_id, characteristic_id, is_required, sort_order)
    VALUES
      (p_door, c_lock,   true,  0),
      (p_door, c_color,  true,  1),
      (p_door, c_width,  false, 2),
      (p_door, c_height, false, 3),
      (p_door, c_hinges, true,  4);

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. CHARACTERISTIC CLASS + MEMBERS + PRODUCT LINK
-- ═══════════════════════════════════════════════════════════════════════════
  INSERT INTO public.characteristic_classes (tenant_id, name, sort_order)
    VALUES (sys_tid, 'Čelična vrata', 0)
    RETURNING id INTO cls_door;

  INSERT INTO public.characteristic_class_members (class_id, characteristic_id, sort_order)
    VALUES
      (cls_door, c_lock,   0),
      (cls_door, c_color,  1),
      (cls_door, c_width,  2),
      (cls_door, c_height, 3),
      (cls_door, c_hinges, 4);

  INSERT INTO public.product_classes (product_id, class_id, sort_order)
    VALUES (p_door, cls_door, 0);

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. PRICING FORMULA
--    Total = base_price + lock_mod + colour_mod + hinge_mod
--            + (width_mm × height_mm × 0.00008)
--    At 900 × 2100 mm the area term adds ~151 EUR on top of 850 base.
-- ═══════════════════════════════════════════════════════════════════════════
  INSERT INTO public.pricing_formulas
    (tenant_id, product_id, name, formula, is_active, sort_order)
    VALUES (
      sys_tid, p_door,
      'Ukupna cijena',
      jsonb_build_object(
        'type', 'add',
        'left', jsonb_build_object(
          'type', 'add',
          'left', jsonb_build_object(
            'type', 'add',
            'left', jsonb_build_object(
              'type', 'add',
              'left',  jsonb_build_object('type', 'base_price'),
              'right', jsonb_build_object('type', 'modifier', 'char_id', c_lock::text)
            ),
            'right', jsonb_build_object('type', 'modifier', 'char_id', c_color::text)
          ),
          'right', jsonb_build_object('type', 'modifier', 'char_id', c_hinges::text)
        ),
        'right', jsonb_build_object(
          'type', 'multiply',
          'left', jsonb_build_object(
            'type', 'multiply',
            'left',  jsonb_build_object('type', 'input', 'char_id', c_width::text),
            'right', jsonb_build_object('type', 'input', 'char_id', c_height::text)
          ),
          'right', jsonb_build_object('type', 'number', 'value', 0.00008)
        )
      ),
      true, 0
    );

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. VISUALIZATION ASSET (default 3D model)
--
--    mesh_rules encodes:
--      • visibility rules  → show named mesh only when its value_id is selected
--      • dimension rules   → scale Door_Assembly node along X (width) and Y
--                            (height) according to the numeric inputs
--
--    Mesh names match those generated by scripts/generate_steel_door_model.mjs.
--    Upload that file to Supabase Storage and replace the url below.
-- ═══════════════════════════════════════════════════════════════════════════
  INSERT INTO public.visualization_assets (
    tenant_id, product_id, characteristic_value_id,
    asset_type, url, is_default, sort_order, mesh_rules
  ) VALUES (
    sys_tid, p_door, NULL,
    '3d_model',
    'https://placeholder.invalid/steel_door.glb',
    true, 0,
    jsonb_build_array(
      -- ── Lock visibility ────────────────────────────────────────────────
      jsonb_build_object('type','visibility','mesh_name','Lock_Cylinder',  'value_id', v_lock_cyl::text),
      jsonb_build_object('type','visibility','mesh_name','Lock_Multipoint','value_id', v_lock_multi::text),
      jsonb_build_object('type','visibility','mesh_name','Lock_Smart',     'value_id', v_lock_smart::text),

      -- ── Colour visibility (one door-leaf mesh per colour) ───────────────
      jsonb_build_object('type','visibility','mesh_name','Door_Leaf_Black',      'value_id', v_col_black::text),
      jsonb_build_object('type','visibility','mesh_name','Door_Leaf_Anthracite', 'value_id', v_col_anthr::text),
      jsonb_build_object('type','visibility','mesh_name','Door_Leaf_White',      'value_id', v_col_white::text),

      -- ── Hinge visibility (three hinges per set) ────────────────────────
      jsonb_build_object('type','visibility','mesh_name','Hinge_Standard_A',  'value_id', v_hng_std::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Standard_B',  'value_id', v_hng_std::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Standard_C',  'value_id', v_hng_std::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Concealed_A', 'value_id', v_hng_conc::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Concealed_B', 'value_id', v_hng_conc::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Concealed_C', 'value_id', v_hng_conc::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Heavy_A',     'value_id', v_hng_heavy::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Heavy_B',     'value_id', v_hng_heavy::text),
      jsonb_build_object('type','visibility','mesh_name','Hinge_Heavy_C',     'value_id', v_hng_heavy::text),

      -- ── Width dimension (scale Door_Assembly in X, range 700–1200 mm) ──
      jsonb_build_object(
        'type','dimension',
        'node_name','Door_Assembly',
        'characteristic_id', c_width::text,
        'axis','x',
        'value_min', 700,  'value_max', 1200,
        'scale_min', 0.778,'scale_max', 1.333
      ),

      -- ── Height dimension (scale Door_Assembly in Y, range 1900–2400 mm)─
      jsonb_build_object(
        'type','dimension',
        'node_name','Door_Assembly',
        'characteristic_id', c_height::text,
        'axis','y',
        'value_min', 1900,  'value_max', 2400,
        'scale_min', 0.905, 'scale_max', 1.143
      )
    )
  );

END $$;
